### ISSUE TITLE
API refactor

### ISSUE THREAD

**Issue by yorickdowne** [eth-educators/ethstaker-deposit-cli#120]
From https://github.com/ethereum/staking-deposit-cli/issues/408

“The API is full of inconsistent type usage, some numbers are hex encoded, others are not, some are strings, some are not, ...

It would be great if future API versions could transition to use the proper hexutil types where appropriate and thereby getting rid of this mess.

Originally posted by @Nichebiche in https://github.com/flashbots/mev-geth/issues/145#issuecomment-2185621606”

Would be good to have this done before audit in October.

This sounds like a breaking change. If we go for it, we may consider a version 3.x right after audit, to signal that we are breaking API from upstream 2.x

**Comment by yorickdowne** [comment]
This appears to be nonsense, or at least not related to staking-deposit-cli at all

https://github.com/flashbots/mev-geth/issues/145#issuecomment-2185621606

**Comment by Nichebiche** [comment]
Sorry I don’t know what I’m doing
