### ISSUE TITLE
CNAME for docs

### ISSUE THREAD

**Issue by yorickdowne** [eth-educators/ethstaker-deposit-cli#125]
Docs live at https://eth-educators.github.io/ethstaker-deposit-cli/ .

We could set up a CNAME deposit-cli.ethstaker.cc and inform GitHub pages of it.

Can I have input from @hanniabu , @remyroy and @valefar-on-discord and once we’ve all bikeshed the sub-domain name sufficiently, I’ll offer a PR for it.

**Comment by hanniabu** [comment]
I'm not a fan of dashes in domains/subdomains, but I'm not sure how else it can be put that's also clear so I suppose deposit-cli.ethstaker.cc is fine with me

**Comment by yorickdowne** [comment]
depositoooor.ethstaker.cc has no dashes but might be confusing ….

**Comment by yorickdowne** [comment]
@hanniabu Can you please create a `CNAME` entry for `deposit-cli.ethstaker.cc` pointing to `eth-educators.github.io`

**Comment by remyroy** [comment]
I don't have a strong opinion on this. I just added a CNAME entry for deposit-cli.ethstaker.cc pointing to eth-educators.github.io but it might take a while to get picked up.

**Comment by remyroy** [comment]
https://deposit-cli.ethstaker.cc/ now works for the documentation website.
