### ISSUE TITLE
Replace mentions of "execution address" for "withdrawal address"

### ISSUE THREAD

**Issue by maraoz** [eth-educators/ethstaker-deposit-cli#133]
Hi there! Good to find that there's a maintained version of deposit-cli.

I was using the tool and got a little confused by the message:
"Repeat your execution address for confirmation."

when I had entered a `--withdrawal_address`  in the cli.

This goes against an age-old UX heuristic, which I'll copy here:

> **Consistency and Standards**
> Users should not have to wonder whether different words, situations, or actions mean the same thing.

I found that there's a couple of mentions of "execution address" in the user interface, which I think could be replaced with "withdrawal address" to improve UX. 

I'd love to help by creating a PR to do this.
Would maintainers be OK with this approach?

**Comment by yorickdowne** [comment]
I think this improves things yes. When you do the PR, look through the documentation in README, docs and intl json files as well please, to see whether any wording there should be changed.
