### ISSUE TITLE
On Ubuntu 24.04, clearing the scrollback with tput fails with the bundled/built binary from Github

### ISSUE THREAD

**Issue by remyroy** [eth-educators/ethstaker-deposit-cli#163]
Here is what I see in my console when the call is made with the regular terminal:

```
tput: /tmp/_MEI3OZe8M/libtinfo.so.6: version `NCURSES6_TINFO_6.2.20211010' not found (required by tput)
```

Simply calling `tput reset` in the same terminal does work for some reason.

That's the result I get from using [the binary](https://github.com/eth-educators/ethstaker-deposit-cli/actions/runs/10925219471/artifacts/1948587911) from this run https://github.com/eth-educators/ethstaker-deposit-cli/actions/runs/10925219471 .

Have you tried this on Ubuntu 24.04 @yorickdowne ? Maybe it's the binary bundle that links to a static lib that isn't present on my system?

**Comment by remyroy** [comment]
The clearing part does work when I call it from my dev environment on the same machine with `uv run ethstaker_deposit/deposit.py new-mnemonic` for instance. So it seems to be related to building/bundling part of the binaries.

**Comment by yorickdowne** [comment]
Always something … only tried it directly, not as a binary.

**Comment by yorickdowne** [comment]
I’m pondering what’s going on - it should check for presence of tput and then just call the system tput directly. Unclear what it’s doing with the ncurses library, and how that relates to the binary.

**Comment by remyroy** [comment]
Do you get the same issue when you try to run the bundled binary? Maybe bundling adds a version of tput or ncurses that causes this issue. I'll try to explore this on my side too.

**Comment by yorickdowne** [comment]
Ubuntu 20 has libtinfo.so.5

Let’s see what’s in the bundled file. We may need to exclude libtinfo in particular when using pyinstaller, though the docs don’t say how. See https://pyinstaller.org/en/stable/spec-files.html#posix-specific-options on how to exclude everything and include some … we want the opposite, exclude some.

**Comment by yorickdowne** [comment]
- I can reproduce this
- If I manually remove `libtinfo.so.6` from the extracted dir in `/tmp` before running `./deposit`, the issue doesn't occur

-> We need to figure out how to exclude `libtinfo` from the binary package

**Comment by yorickdowne** [comment]
I have a PR with exclusion. That should work on all versions of Debian (11, 12; Ubuntu 20, 22, 24), but we need to check that now excluding `libtinfo.so.6` doesn't hinder us in another way.
