### ISSUE TITLE
Internet connectivity warning on load

### ISSUE THREAD

**Issue by valefar-on-discord** [eth-educators/ethstaker-deposit-cli#17]
There should be a check when loading the CLI application for an internet connection and warn the user if so.

Few thoughts:
- A ping to google.com would probably be sufficient for a test
- Not 100% on the UX but my initial idea is if a connection is detected a warning explaining the concerns would be presentend and the user would be required to press a key to continue
- An optional argument should be accepted to ignore this check for user who know what they are doing. This will also help with resolving unit test failures

**Comment by remyroy** [comment]
There are a few pitfalls when testing or detecting an internet connection. Some countries block connections to various website and it might show as *offline* even though that person could be online. There is some exploration to be done and one of them could be to check how we do it with Wagyu Key Gen or if we are using a library how that library does it.

**Comment by remyroy** [comment]
Here is some documentation on how browsers do it: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine

**Comment by remyroy** [comment]
The *By using an IP address/By using socket package* section from https://www.codespeedy.com/how-to-check-the-internet-connection-in-python/ might be useful.
