### ISSUE TITLE
Rework ValidationError and replace the related traceback with a nice error message

### ISSUE THREAD

**Issue by remyroy** [eth-educators/ethstaker-deposit-cli#18]
A traceback should be not shown or raised when some of the ValidatorError are raised across different command flows. Instead, there should be a nice error message shown to the user.

**Comment by valefar-on-discord** [comment]
If we want to hide the stack traces across the board, we could use `sys.tracebacklimit = 0` in `deposit.py`
That would result in something like:

```
Please enter your mnemonic separated by spaces (" "). Note: you only need to enter the first 4 letters of each word if you'd prefer.:    
ethstaker_deposit.exceptions.ValidationError: That is not a valid mnemonic, please check for typos.
```

**Comment by remyroy** [comment]
`sys.tracebacklimit = 0` seems too radical. Instead, I would try to catch our `ethstaker_deposit.exceptions.ValidationError` exception globally and output the content of the error message.
