### ISSUE TITLE
Clipboard or terminal scrollback mnemonic vulnerability

### ISSUE THREAD

**Issue by valefar-on-discord** [eth-educators/ethstaker-deposit-cli#32]
Forward from 
- https://github.com/ethereum/staking-deposit-cli/issues/97

The [2020 Audit of staking-deposit-cli](https://github.com/trailofbits/publications/blob/master/reviews/ETH2DepositCLI.pdf) mentioned a task to properly clear the terminal buffer and clipboard to prevent the possibility of leaking the mnemonic.  This was investigated by Carl and he has concerns around cross-platform solutions.

Ultimately it may not be possible to resolve this for every usecase but something that should be investigated as is a likely output from any future audit.

**Comment by remyroy** [comment]
My last comment is probably more related to #33
