### ISSUE TITLE
Improve documentation readability

### ISSUE THREAD

**Issue by valefar-on-discord** [eth-educators/ethstaker-deposit-cli#39]
Forward from:
- https://github.com/ethereum/staking-deposit-cli/issues/166

The README is not exactly ideal and can be greatly improved. I feel a separate website for documentation might be warranted but perhaps a reorganization of the README could suffice.

**Comment by valefar-on-discord** [comment]
I've been playing around adding this to ethstaker.cc as a separate page similar to https://ethstaker.cc/staking-software/wagyu

Here is an very rough draft of it:
<img width="1378" alt="Screenshot 2024-05-27 at 8 49 38 AM" src="https://github.com/eth-educators/ethstaker-deposit-cli/assets/124839138/b88f8408-d633-42aa-87f1-fb8e7f4d7b03">

Does this seem acceptable or do we think there is a superior approach?  

I'd add installation instructions as well and I'm thinking about having a OS selection at the start that will modify the documentation

**Comment by remyroy** [comment]
I'd love to have a separate website for documentation. There are a bunch or great tools for this: [readthedocs](https://about.readthedocs.com/) and [mdBook](https://rust-lang.github.io/mdBook/) are two of the great ones that can integrate with the repository.

**Comment by remyroy** [comment]
I believe we could also host this for free on Github pages and have a workflow generate it automatically. See https://stackoverflow.com/questions/62683329/how-to-self-host-read-the-docs-using-github-pages for instance.

**Comment by remyroy** [comment]
https://docusaurus.io/ could be another tool for this

**Comment by valefar-on-discord** [comment]
Played around with mdBook and this was the result: https://valefar-on-discord.github.io/ethstaker-deposit-cli/index.html

**Comment by remyroy** [comment]
I really like the style and result of mdBook. I might have slight preference for mdBook over readthedocs but I don't know a good informed opinion about the underlying tech or features.
