### ISSUE TITLE
Add amount parameter for deposit

### ISSUE THREAD

**Issue by remyroy** [eth-educators/ethstaker-deposit-cli#53]
Forwarded from:

- https://github.com/ethereum/staking-deposit-cli/pull/326

This is potentially confusing and there should be a very conservative approach to take and implement this.

**Comment by yorickdowne** [comment]
Original requester says partial-deposit meets their needs. Makes sense to me. This is an advanced workflow and so reasonably:

- Standard workflow does 32 ETH; good UX
- Advanced users can then then partial-deposit the amount they want and use that file

Waiting for confirmation, and, potentially this is solved by Valefar’s new command.

**Comment by remyroy** [comment]
#89 should partially resolve this.

We have too many concerns modifying this on the `new-mnemonic`.
