### ISSUE TITLE
Coroutine raised StopIteration ci-runner error

### ISSUE THREAD

**Issue by valefar-on-discord** [eth-educators/ethstaker-deposit-cli#62]
After landed #48  I noticed the ci-runner failed with a non-assertion error but a `RuntimeError: coroutine raised StopIteration` 
https://github.com/valefar-on-discord/ethstaker-deposit-cli/actions/runs/9331869782/job/25687038382

I tried to reproduce this locally to no avail and I haven't seen it since from git actions but something to keep a look out for

**Comment by valefar-on-discord** [comment]
Saw the exact failure again: https://github.com/valefar-on-discord/ethstaker-deposit-cli/actions/runs/9438041063/job/25994595794

**Comment by remyroy** [comment]
I believe I just reproduced this issue on https://github.com/remyroy/ethstaker-deposit-cli/actions/runs/9451804698/job/26033609500

**Comment by remyroy** [comment]
This seems to be related to the use of pipes in asyncio.create_subprocess_shell. The only tests failing are those that uses pipes (only 2, `test_script_abbreviated_mnemonic` and `test_script_bls_withdrawal` in `tests/test_cli/test_new_mnemonic.py`)

**Comment by yorickdowne** [comment]
">Is there a way/workaround to get this fixed in python 3.8 and python 3.9?

The patch should be easy enough to back port, but that's not something we'll do because this is not a security issue.

In your own code you could monkey patch multiprocessing, in particular by patching the Listener class to use a larger backlog."

https://github.com/python/cpython/issues/101225

**Comment by yorickdowne** [comment]
I think we can reasonably wontfix this. It doesn't impact running deposit on macOS with Python 3.9, just the test suite. If we're keen we can exclude two tests on that platform.

**Comment by yorickdowne** [comment]
I'm closing this as wontfix: The workaround of skipping those two tests on macOS Python 3.9 seems reasonable to me, and Python 3.9 is not getting the fix for it back-ported.
