### ISSUE TITLE
Partial Deposit Command

### ISSUE THREAD

**Issue by valefar-on-discord** [eth-educators/ethstaker-deposit-cli#89]
With the addition of EIP-7251 I can easily see a world where users will want to deposit an additional amount to their 0x02 validators. From what I understand those deposits will still have to go through the normal activation queue for security purposes: ["EIP-7251 requires partial deposits to go through the activation queue and rate-limits top-ups with the weight-based rate-limiting mechanism"](https://ethereum2077.substack.com/i/140556227/partial-deposits-and-withdrawals-under-eip)

Because the deposit is ultimately signed by the validator key it would be better to create a separate command for topping up instead of using the current deposit path which requires the mnemonic.

We should create a new command `partial-deposit` or similarly named where an amount and keystore file can be provided that will return a deposit signature. Due to the smart contract, this will require a 1ETH minimum:
`require(msg.value >= 1 ether, "DepositContract: deposit value too low");`

For the amount field we can allow decimals but it has to be in multiples by gwei:
`require(msg.value % 1 gwei == 0, "DepositContract: deposit value not multiple of gwei");`

**Comment by valefar-on-discord** [comment]
This would also resolve the concerns of #53 in that the user can create the validator keys as normal and then use those validator keys to create a separate deposit.

I believe the only method available to create a 0x02 validator is from a pre-existing validator through the execution layer. This would mean the use case of a non-32 ETH deposit is quite limited and this as a work around would be sufficient.

**Comment by valefar-on-discord** [comment]
One note is the withdrawal credentials are going to be a required parameter even though the user may be confused as to why:
https://github.com/ethereum/consensus-specs/blob/dev/specs/electra/beacon-chain.md#new-is_valid_deposit_signature

**Comment by valefar-on-discord** [comment]
After spending some time investigating this, it looks like some changes have happened that will likely invalidate the need for this specific feature versus adding an amount as requested in #53.

It looks like a number of operations such as consolidation are going to be EL-triggered using EIP-7685 request framework where authorization is determined by the withdrawal address.

This means you can sign your partial deposits using your withdrawal address instead of your validator key.  Given that the need for validator key signatures for this purpose is likely minimal.

**Comment by yorickdowne** [comment]
@valefar-on-discord, the credentials don’t get changed after initial deposit. So for additional deposits, wouldn’t even 0x00 credentials be sufficient?

**Comment by yorickdowne** [comment]
Has the partial deposit command been tested on Holesky? Against 0x00 and 0x01 validators, with matching or differing withdrawal credentials?

**Comment by remyroy** [comment]
I created a few Holesky validators to test with this. Will this only be possible in electra?

**Comment by valefar-on-discord** [comment]
> @valefar-on-discord, the credentials don’t get changed after initial deposit. So for additional deposits, wouldn’t even 0x00 credentials be sufficient?

The only reason I didn't allow 0x00 credentials for this command was there is no way to validate them without the public key of the mnemonic.  Looking at it again I don't think that is a concern.  Would have to update a few items but should be easy enough to allow.

**Comment by valefar-on-discord** [comment]
> I created a few Holesky validators to test with this. Will this only be possible in electra?

There should be nothing stopping from this working prior to electra from my memory. The output of a partial deposit if an amount of 32 is provided would be identical to a standard 32 deposit.

**Comment by remyroy** [comment]
I just tried 2 transactions to add to an existing validator on holesky:

- Adding 1 ETH to a validator with a 0x00 withdrawal credentials: https://holesky.etherscan.io/tx/0x8e17114102e12ccd18abb9c3ec2ea6cca9264db5b0bd8990108db8840d53936a
- Adding 2 ETH to the same validator after performing a BLS to execution change: https://holesky.etherscan.io/tx/0xabb189081ddd7c502e97ff85b444a0c7f57a02db82380a8ba09eea53339776fa

I'll monitor on https://holesky.beaconcha.in/validator/1804776 to see the balance.

**Comment by remyroy** [comment]
To test this, I went to https://playground.ethers.org/ with a browser with MetaMask (on Holesky) and I used these commands:
```javascript
provider = new ethers.providers.Web3Provider(window.ethereum)
await provider.send("eth_requestAccounts", [])
signer = provider.getSigner()
abi = [{"inputs":[],"stateMutability":"nonpayable","type":"constructor"},{"anonymous":false,"inputs":[{"indexed":false,"internalType":"bytes","name":"pubkey","type":"bytes"},{"indexed":false,"internalType":"bytes","name":"withdrawal_credentials","type":"bytes"},{"indexed":false,"internalType":"bytes","name":"amount","type":"bytes"},{"indexed":false,"internalType":"bytes","name":"signature","type":"bytes"},{"indexed":false,"internalType":"bytes","name":"index","type":"bytes"}],"name":"DepositEvent","type":"event"},{"inputs":[{"internalType":"bytes","name":"pubkey","type":"bytes"},{"internalType":"bytes","name":"withdrawal_credentials","type":"bytes"},{"internalType":"bytes","name":"signature","type":"bytes"},{"internalType":"bytes32","name":"deposit_data_root","type":"bytes32"}],"name":"deposit","outputs":[],"stateMutability":"payable","type":"function"},{"inputs":[],"name":"get_deposit_count","outputs":[{"internalType":"bytes","name":"","type":"bytes"}],"stateMutability":"view","type":"function"},{"inputs":[],"name":"get_deposit_root","outputs":[{"internalType":"bytes32","name":"","type":"bytes32"}],"stateMutability":"view","type":"function"},{"inputs":[{"internalType":"bytes4","name":"interfaceId","type":"bytes4"}],"name":"supportsInterface","outputs":[{"internalType":"bool","name":"","type":"bool"}],"stateMutability":"pure","type":"function"}]
contract = new Contract("0x4242424242424242424242424242424242424242", abi, signer)
```

To send a 1 ETH partial deposit, I than did:
```javascript
eth = parseEther("1.0")
tx = await contract.deposit("0x962195958e742b8dc5b2a25adede82fc5cd661827cb1e1237025e3d7847801aa5584d5bfdc6893413264cccfbff54128", "0x0100000000000000000000004d496ccc28058b1d74b7a19541663e21154f9c84", "0x98ba9561782653197e00a3fff8163a50fbbac42846782f0653915bb2b6f23edece981f1ebec81372232473f35acfd94d0833c4046f5e17aac17f5370468105854c4dac721c52af67f907761f6ed67495170b9016c79ab02b72c37143e5485b19", "0x90028e8fb10ca5263b465fe73a1d798828876760cf359efedfdce4dd9e268e5b", { value: eth })
```
In that last call, the parameters are (in order):
1. pubkey
2. withdrawal_credentials
3. signature
4. deposit_data_root

**Comment by remyroy** [comment]
The balance of my validator above seems to have been increased by 3 ETH so everything seems good.
