### ISSUE TITLE
Version increments

### ISSUE THREAD

**Issue by valefar-on-discord** [eth-educators/ethstaker-deposit-cli#92]
We have two versions that exist in the application:
[setup.py](https://github.com/eth-educators/ethstaker-deposit-cli/blob/main/setup.py) and [settings.py](https://github.com/eth-educators/ethstaker-deposit-cli/blob/main/ethstaker_deposit/settings.py#L4)

We can manually update these each time we release or we can use version tools to help automate it.

**Comment by remyroy** [comment]
I would highly value this being located in a single place of truth. Git tags is a great way to do it but propagating it around can be tricky. I'll investigate this.

**Comment by remyroy** [comment]
I think having the single source of truth for the version in the `pyproject.toml` file is the way to go. Github tags (used for releases mostly, starting with `v`) can confirm that truth. The `setup.py` file was removed and mostly replaced with the `pyproject.toml` file. Let me see how to remove or pull the version number in `settings.py`.
